### ISSUE TITLE
Document is missing OCcas and OCmdex details

### ISSUE THREAD

**Issue by brakon** [kpath/Vagrant-CRS#2]
Readme does not mentioned how to obtain the following files:
├── OCcas11.1.0-Linux64.sh
├── OCmdex6.5.1-Linux64_829811.sh

**Comment by brakon** [comment]
Readme should include these fiels can be retrieved in e-delivery "Oracle Endeca Guided Search"

**Comment by grahammather** [comment]
I think the downloads page on Oracle eDelivery has changed.  I will update the readme.
